SC_INC = -I$(PROJ_SC_HOME)/include -I$(PROJ_SC_HOME)/tb -I$(PROJ_SC_HOME)/rtl
SC_SIM_FILES = sim.cpp
SC_BUILD_LOG = dff.build.$(TEST_NAME).log
SC_SIM_LOG = dff.sim.$(TEST_NAME).log
MOD=dff

include $(PROJ_SC_HOME)/rtl/Makefile
include $(PROJ_SC_HOME)/tb/Makefile
include $(WS_ROOT)/include/Makefile
